version: '3'
services:
  media-portfolio:
    build: ./docker/node
    container_name: media.portfolio
    command: tail -f /dev/null
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

  nginx:
    build: ./docker/nginx
    container_name: media.portfolio.nginx
    volumes:
      - .:/usr/src
    ports:
      - "3007:80"

  ghost:
    image: ghost:1-alpine
    container_name: media.portfolio.ghost
    ports:
      - 80:2368
    environment:
      url: http://localhost
      database__client: mysql
      database__connection__host:
      database__connection__user: root
      database__connection__password: admin
      database__connection__database: ghost
